/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shifr;

/**
 *
 * @author KL
 */
public class FormBloch extends javax.swing.JFrame {

    /**
     * Creates new form FormBloch
     */
    public FormBloch() {
        initComponents();
    }

    private static void aswap(char[] pa, int i, int j) {
        char k = pa[i];
        pa[i] = pa[j];
        pa[j] = k;
    }

    private static String arraout(char[] pa, int i) {
        String s = "";

        for (char a : pa) {
            s += a;
        }

        s = s.substring(0, s.length());
        return s;

    }

    private static String prmt(char[] pa, int i, int k, int ik) {
//        if (ik == k) {

//            return;
//        }
        for (int j = i; j < pa.length; j++) {
            ik++;

            aswap(pa, i, j);
            //System.out.println(ik + " " + k);
            if (ik == k) {

                break;
            }
            prmt(pa, i + 1, k, ik);
            aswap(pa, i, j);
        }
        String textInput = arraout(pa, i);
        return textInput;
    }
//    private static char[] splitString(){
//        
//        return elem;
//}

    private static String blockShifr(String textInput, Integer k) {
        //        String textInput = jTextField1.getText();
//        Integer k = Integer.valueOf(jTextField2.getText());
//        String str = "11 34 3 45 23 5 67";
//        String strArr[] = textInput.split(" ");
//        int pa[] = new int[strArr.length];
//        for (int i = 0; i < strArr.length; i++) {
//            pa[i] = Integer.parseInt(strArr[i]);

        // System.out.println(numArr[i]);
//        }
        //String textInput = jTextField1.getText();
        char pa[] = textInput.toCharArray();
        //Integer k = Integer.valueOf(jTextField2.getText());
        String block = prmt(pa, 0, k, 0);
        return block;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String textOutPut = "";
        String text;
        String textInput = jTextField1.getText();
        Integer k = Integer.valueOf(jTextField2.getText());
        Integer nblock = Integer.valueOf(jTextField3.getText());
        int raz=textInput.length();
        if (textInput.length()%nblock==0){
            for (int i = 0, j = nblock; i < textInput.length(); i = i + nblock, j = j + nblock) {
                text = textInput.substring(i, j);
                char[] pa = text.toCharArray();
                textOutPut = textOutPut + prmt(pa, 0, k, 0).toString();
            }
        }
        else{
            while(raz>=0){
            raz=raz-nblock;
            }
            for(int i=0;i>raz;i--){
                textInput=textInput+'#';
            }  
            for (int i = 0, j = nblock; i < textInput.length(); i = i + nblock, j = j + nblock) {
                text = textInput.substring(i, j);
                char[] pa = text.toCharArray();
                textOutPut = textOutPut + prmt(pa, 0, k, 0).toString();
            }
        }
        jTextField4.setText(textOutPut);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBloch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBloch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBloch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBloch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBloch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
